function createFactors(~,~, obj)

[factorName, nbFactors] = createFactorPrompt1;

if ~strcmp(nbFactors, '?')
    sampleName = obj.model.nameList{1};

    rowNames = Table.create(zeros(length(obj.model.nameList), 1), 'rowNames',  obj.model.nameList);
    
    [start, number, name] = createFactorPrompt2(1, sampleName);
    
    factorTbl = parseFactorFromRowNames(rowNames, start, number, name);
    
    if nbFactors > 1
        for i = 2:nbFactors
            [start, number, name] = createFactorPrompt2(i, sampleName);

            factorTbl = horzcat(factorTbl, parseFactorFromRowNames(rowNames, start, number, name));
        end
    end
    
    factorTbl.name = factorName;
    obj.model.factorTable = factorTbl;
    disp(obj.model.factorTable.levels);
    updateMenus(obj);
    
end


    function [factorName, nbFactors] = createFactorPrompt1
        
        factorName = '?';
        nbFactors = '?';
        
        pos = getMiddle(gcf, 250, 165);

        d = dialog('position', pos, ...
                       'name', 'Enter number of factors');

        uicontrol('parent', d, ...
                'position', [30 115 90 20], ...
                   'style', 'text', ...
                  'string', 'Factor name :', ...
                'fontsize', 10, ...
     'horizontalalignment', 'right');

        edit1 = uicontrol('Parent', d, ...
                        'Position', [130 116 90 20], ...
                           'Style', 'edit');
                       
        uicontrol('parent', d,...
                'position', [30 80 90 20], ...
                   'style', 'text',...
                  'string', 'Nb of factors :', ...
                'fontsize', 10, ...
     'horizontalalignment', 'right');

        edit2 = uicontrol('parent', d,...
                       'position', [130 81 90 20], ...
                          'style', 'edit');

        error = uicontrol('parent', d,...
                        'position', [135 46 85 25], ...
                           'style', 'text',...
                          'string', 'Invalid value', ...
                 'foregroundcolor', 'r', ...
                         'visible', 'off', ...
                        'fontsize', 8);

        uicontrol('parent', d, ...
                'position', [30 30 85 25], ...
                  'string', 'Validate', ...
                'callback', @callback);

        uicontrol('parent', d, ...
                'position', [135 30 85 25], ...
                  'string', 'Cancel', ...
                'callback', 'delete(gcf)');

        % Wait for d to close before running to completion
        uiwait(d);

        function callback(~,~)
            if ~isnan(str2double(get(edit2,'String')))
                factorName = get(edit1, 'string');
                nbFactors = str2double(get(edit2,'String'));
                delete(gcf);
            else
                set(error, 'visible', 'on');
            end
        end
    end

    function [start, number, name] = createFactorPrompt2(index, sample)
        
        start = '?';
        number = '?';
        name = '?';
        
        pos = getMiddle(gcf, 250, 235);

        d = dialog('position', pos, ...
                       'name', ['Factor number : ' num2str(index)]);

        uicontrol('parent', d, ...
                'position', [30 185 200 20], ...
                   'style', 'text', ...
                  'string', sample, ...
                'fontsize', 10);

        uicontrol('parent', d, ...
                'position', [30 150 90 20], ...
                   'style', 'text', ...
                  'string', 'Factor start :', ...
                'fontsize', 10, ...
     'horizontalalignment', 'right');

        edit1 = uicontrol('Parent', d, ...
                        'Position', [130 151 90 20], ...
                           'Style', 'edit');

        uicontrol('parent', d, ...
                'position', [30 115 90 20], ...
                   'style', 'text', ...
                  'string', 'Factor length :', ...
                'fontsize', 10, ...
     'horizontalalignment', 'right');

        edit2 = uicontrol('Parent', d, ...
                        'Position', [130 116 90 20], ...
                           'Style', 'edit');

        uicontrol('parent', d,...
                'position', [30 80 90 20], ...
                   'style', 'text',...
                  'string', 'Factor name :', ...
                'fontsize', 10, ...
     'horizontalalignment', 'right');

        edit3 = uicontrol('parent', d,...
                       'position', [130 81 90 20], ...
                          'style', 'edit');

        error = uicontrol('parent', d,...
                        'position', [135 46 85 25], ...
                           'style', 'text',...
                          'string', 'Invalid value', ...
                 'foregroundcolor', 'r', ...
                         'visible', 'off', ...
                        'fontsize', 8);

        uicontrol('parent', d, ...
                'position', [30 30 85 25], ...
                  'string', 'Validate', ...
                'callback', @callback);

        uicontrol('parent', d, ...
                'position', [135 30 85 25], ...
                  'string', 'Cancel', ...
                'callback', 'delete(gcf)');

        % Wait for d to close before running to completion
        uiwait(d);

        function callback(~,~)
            check = 0;
            if ~isnan(str2double(get(edit1,'String')))
                start = str2double(get(edit1,'String'));
                check = check + 1;
            end
            if ~isnan(str2double(get(edit2,'String')))
                number = str2double(get(edit2,'String'));
                check = check + 1;
            end
            if check == 2
                name = get(edit3, 'string');
                delete(gcf);
            else
                set(error, 'visible', 'on');
            end
        end
    end

end