function axe = contoursRotatePrompt

    pos = getMiddle(gcf, 250, 130);
    
    d = dialog('position', pos, ...
                   'name', 'Select axis of rotation');
    
    uicontrol('parent', d, ...
            'position', [30 80 90 20], ...
               'style', 'text', ...
              'string', 'Axis :', ...
            'fontsize', 10, ...
 'horizontalalignment', 'right');
       
    popup = uicontrol('parent', d, ...
                    'position', [130 82 90 20], ...
                       'style', 'popup', ...
                      'string', {'x-axis', 'y-axis'});
       
    uicontrol('parent', d, ...
            'position', [30 30 85 25], ...
              'string', 'Cancel', ...
            'callback', 'delete(gcf)');
        
    uicontrol('parent', d, ...
            'position', [135 30 85 25], ...
              'string', 'Validate', ...
            'callback', @callback);
        
    % Wait for d to close before running to completion
    uiwait(d);
   
    function callback(~,~)
        axe = popup.Value;
        delete(gcf);
    end
end