function resol = contoursConvertPxMmPrompt

    pos = getMiddle(gcf, 250, 130);
    
    d = dialog('position', pos, ...
                   'name', 'Enter image resolution');
    
    uicontrol('parent', d,...
            'position', [30 80 90 20], ...
               'style', 'text',...
              'string', 'Resolution :', ...
            'fontsize', 10, ...
 'horizontalalignment', 'right');
       
    edit = uicontrol('parent', d,...
                   'position', [130 81 90 20], ...
                      'style', 'edit');
                  
    error = uicontrol('parent', d,...
                    'position', [135 46 85 25], ...
                       'style', 'text',...
                      'string', 'Invalid value', ...
             'foregroundcolor', 'r', ...
                     'visible', 'off', ...
                    'fontsize', 8);
       
    uicontrol('parent', d,...
            'position', [30 30 85 25], ...
              'string', 'Cancel',...
            'callback', 'delete(gcf)');
        
    uicontrol('parent', d,...
            'position', [135 30 85 25], ...
              'string', 'Validate',...
            'callback', @callback);
        
    % Wait for d to close before running to completion
    uiwait(d);
   
    function callback(~,~)
        try
            if ~isnan(str2double(get(edit,'String')))
                resol = eval(get(edit,'String'));
                delete(gcf);
            else
                if find(ismember(get(edit,'String'), ['\', '¨', '/', '*', '+', '-'])) ~= 0
                    resol = eval(get(edit,'String'));
                    delete(gcf);
                else
                    set(error, 'visible', 'on');
                end
            end
        catch
            set(error, 'visible', 'on');
        end
    end
end
