function loop = importFactorsPrompt
    loop = 0;

    pos = getMiddle(gcf, 400, 130);
    
    d = dialog('position', pos, ...
                   'name', 'Error');
    
    uicontrol('parent', d,...
            'position', [30 80 340 20], ...
               'style', 'text',...
              'string', 'The selected factors are not compatible with the datas', ...
            'fontsize', 10);
       
    uicontrol('parent', d,...
            'position', [90 30 100 25], ...
              'string', 'Cancel',...
            'callback', @callback);
        
    uicontrol('parent', d,...
            'position', [210 30 100 25], ...
              'string', 'Choose another',...
            'callback', 'delete(gcf)');
        
    % Wait for d to close before running to completion
    uiwait(d);
   
    function callback(~,~)
        loop = 1;
        delete(gcf);
    end
end
