function setupMenuPolygonsManager(frame)
%SETUPMENUPOLYGONSMANAGER  Creates all the menus of the MainFrame

% create all the main menus
fileMenu = uimenu(frame.handles.figure, 'label', '&File');
editMenu = uimenu(frame.handles.figure, 'label', '&Edit');
factMenu = uimenu(frame.handles.figure, 'label', 'F&actors', 'enable', 'off');
foncMenu = uimenu(frame.handles.figure, 'label', '&Process', 'enable', 'off');
pcaMenu = uimenu(frame.handles.figure, 'label', 'P&ca', 'visible', 'off');
viewMenu = uimenu(frame.handles.figure, 'label', '&View', 'enable', 'off');
contPmenu = uicontextmenu; 
contLmenu = uicontextmenu; 

% build menubar data structure
menubar.file.handle = fileMenu;
menubar.edit.handle = editMenu;
menubar.factors.handle = factMenu;
menubar.process.handle = foncMenu;
menubar.view.handle = viewMenu;
menubar.pca.handle = pcaMenu;


%               ----------------------------------------------------------- FILE

% create all the submenus of the 'file' menu
menubar.file.openFolder.handle = uimenu(fileMenu, ...
    'label', '&Import polygons (folder)', ...
    'callback', @(~,~) importBasicPolygon(frame), ...
    'accelerator', 'N');

menubar.file.openFile.handle = uimenu(fileMenu, ...
    'label', 'Import &concatenated polygons file', ...
    'callback', @(~,~) importCoordsPolygon(frame));
               
menubar.file.openPolarSignatures.handle = uimenu(fileMenu, ...
    'label', '&Import polar signatures file', ...
    'callback', @(~,~) importPolarSignature(frame));

menubar.file.openDemoPolygonList.handle = uimenu(fileMenu, ...
    'label', '&Import demo polygon list', ...
    'callback', @(~,~) importDemoPolygonList(frame), ...
    'separator', 'on');
               
menubar.file.openDemoPolygonArray.handle = uimenu(fileMenu, ...
    'label', '&Import demo polygon Array', ...
    'callback', @(~,~) importDemoPolygonArray(frame));
               
menubar.file.savePolygons.handle = uimenu(fileMenu, ...
    'label', 'Save polygons', ...
    'callback', @(~,~) savePolygons(frame.model), ...
    'enable', 'off', ...
    'accelerator', 'S', ...
    'separator', 'on');

menubar.file.saveMacro.handle = uimenu(fileMenu, 'label', 'Save &macro', ...
                   'callback', @(~,~) saveMacro(frame.model), ...
                     'enable', 'off', ...
                  'separator', 'on', ...
                'accelerator', 'Q');
menubar.file.loadMacro.handle = uimenu(fileMenu, 'label', '&Load macro', ...
                   'callback', @(~,~) loadMacro(frame), ...
                     'enable', 'off');

menubar.file.exportToWorkspace.handle = uimenu(fileMenu, 'label', '&Export datas to workspace', ...
                   'callback', @(~,~) exportToWorkspace(frame), ...
                     'enable', 'off', ...
                  'separator', 'on');

menubar.file.close.handle = uimenu(fileMenu, 'label', '&Close', ...
                   'callback', @(~,~) close(gcf), ...
                  'separator', 'on', ...
                'accelerator', 'p');

%               ----------------------------------------------------------- EDIT

menubar.edit.extractSelection.handle = uimenu(editMenu, 'label', 'E&xtract Selection', ...
                   'callback', @(~,~) extractSelectedPolygons(frame), ...
                     'enable', 'off', ...
                'accelerator', 'D');
              
menubar.edit.clearSelection.handle = uimenu(editMenu, 'label', 'Delete Selection', ...
                   'callback', @(~,~) removeSelectedPolygons(frame), ...
                     'enable', 'off', ...
                'accelerator', 'D');

menubar.edit.duplicate.handle = uimenu(editMenu, 'label', 'Duplicate', ...
                   'callback', @(~,~) duplicatePolygons(frame), ...
                     'enable', 'off', ...
                  'separator', 'on');

menubar.edit.showInfo.handle = uimenu(editMenu, 'label', 'Display &Infos', ...
                   'callback', @(~,~) showTable(frame.model.infoTable), ...
                     'enable', 'on', ...
                  'separator', 'on');



%               ----------------------------------------------------------- FACTORS

% create all the submenus of the 'factors' menu
menubar.factors.import.handle = uimenu(factMenu, 'label', 'Import &factors', ...
                   'callback', @(~,~) importFactors(frame), ...
                'accelerator', 'f');
menubar.factors.create.handle = uimenu(factMenu, 'label', '&Generate factors from names', ...
                   'callback', @(~,~) createFactors(frame));

menubar.factors.save.handle = uimenu(factMenu, 'label', '&Save factors', ...
                   'callback', @(~,~) saveFactors(frame.model), ...
                     'enable', 'off', ...
                  'separator', 'on');

menubar.factors.display.handle = uimenu(factMenu, 'label', '&Display factors', ...
                   'callback', @(~,~) showTable(frame), ...
                     'enable', 'off', ...
                  'separator', 'on');

%               ----------------------------------------------------------- PROCESS

% create all the submenus of the 'process' menu
menubar.process.recenter.handle = uimenu(foncMenu, 'label', 'Re&center polygons', ...
              'callback', @(~,~) polygonsRecenter(frame));

fc1 = uimenu(foncMenu, 'label', 'Rotate &all');
           uimenu(fc1, 'label', '90° &right', ...
                    'callback', @(~,~) polygonsRotate(frame, 90, 'all'));
           uimenu(fc1, 'label', '90° &left', ...
                    'callback', @(~,~) polygonsRotate(frame, 270, 'all'));
           uimenu(fc1, 'label', '&180°', ...
                    'callback', @(~,~) polygonsRotate(frame, 180, 'all'));
menubar.process.rotateAll.handle = fc1;

fc2 = uimenu(foncMenu, 'label', 'Rotate &selection');
           uimenu(fc2, 'label', '90° &right', ...
                    'callback', @(~,~) polygonsRotate(frame, 90, 'selected'));
           uimenu(fc2, 'label', '90° &left', ...
                    'callback', @(~,~) polygonsRotate(frame, 270, 'selected'));
           uimenu(fc2, 'label', '&180°', ...
                    'callback', @(~,~) polygonsRotate(frame, 180, 'selected'));
           uimenu(fc2, 'label', 'Custom angle C&W', ...
                    'callback', @(~,~) polygonsRotate(frame, 'customCW', 'selected'), ...
                   'separator', 'on');
           uimenu(fc2, 'label', 'Custom angle &CCW', ...
                    'callback', @(~,~) polygonsRotate(frame, 'customCCW', 'selected'));
menubar.process.rotateSelected.handle = fc2;

menubar.process.resizePolygons.handle = uimenu(foncMenu, 'label', '&Resize polygons', ...
              'callback', @(~,~) polygonsResize(frame));

menubar.process.simplifyPolygons.handle = uimenu(foncMenu, ...
    'label', 'Sim&plify polygons', ...
    'callback', @(~,~) polygonsSimplify(frame, 'on'), ...
    'separator', 'on');
menubar.process.resamplePolygonsByLength.handle = uimenu(foncMenu, ...
    'label', 'Resample by length', ...
    'callback', @(~,~) polygonsResampleByLength(frame));

menubar.process.alignAroundAxis.handle = uimenu(foncMenu, ...
    'label', 'A&lign around symmetry axis');
uimenu(menubar.process.alignAroundAxis.handle, 'label', '&Precise', ...
    'callback', @(~,~) polygonsAlign(frame, 'precise'));
uimenu(menubar.process.alignAroundAxis.handle, 'label', '&Fast', ...
    'callback', @(~,~) polygonsAlign(frame, 'fast'));


menubar.process.concatenatePolygons.handle = uimenu(foncMenu, ...
    'label', 'C&oncatenate Polygons', ...
    'callback', @(~,~) polygonsConcatenate(frame), ...
    'separator', 'on');

menubar.process.computeSignatures.handle = uimenu(foncMenu, ...
    'label', 'Compute Polar S&ignatures', ...
    'callback', @(~,~) polygonsToSignature(frame));
         
%               ----------------------------------------------------------- PCA

% create all the submenus of the 'pca' menu
menubar.pca.computePCA.handle = uimenu(pcaMenu, 'label', '&Compute PCA', ...
                    'callback', @(~,~) computePCA(frame));

menubar.pca.displayEigenValues.handle = uimenu(pcaMenu, 'label', 'Display &Eigen Values', ...
                    'callback', @(~,~) pcaEigen(frame), ...
                      'enable', 'off', ...
                   'separator', 'on');
menubar.pca.displayScores.handle = uimenu(pcaMenu, 'label', 'Display &Scores', ...
                    'callback', @(~,~) pcaScores(frame), ...
                      'enable', 'off');
menubar.pca.displayLoadings.handle = uimenu(pcaMenu, 'label', 'Display &Loadings', ...
                    'callback', @(~,~) pcaLoadings(frame), ...
                      'enable', 'off');
menubar.pca.influencePlot.handle = uimenu(pcaMenu, 'label', '&Influence Plot', ...
                    'callback', @(~,~) pcaInfluence(frame), ...
                      'enable', 'off');
menubar.pca.displayProfiles.handle = uimenu(pcaMenu, 'label', 'Display &profiles', ...
                    'callback', @(~,~) pcaVector(frame), ...
                      'enable', 'off');

menubar.pca.displayScoresAndProfiles.handle = uimenu(pcaMenu, 'label', '&Display scores + profiles', ...
                    'callback', @(~,~) pcaScoresProfiles(frame), ...
                      'enable', 'off', ...
                   'separator', 'on');
% PCA sub-menu
pca8 = uimenu(pcaMenu, 'label', 'Save pca', ...
                     'enable', 'off');
           uimenu(pca8, 'label', '&Means', ...
                    'callback', @(~,~) savePca(frame.model, 'means'));
           uimenu(pca8, 'label', '&Scores', ...
                    'callback', @(~,~) savePca(frame.model, 'scores'));
           uimenu(pca8, 'label', '&Loadings', ...
                    'callback', @(~,~) savePca(frame.model, 'loadings'));
           uimenu(pca8, 'label', '&Eigen values', ...
                    'callback', @(~,~) savePca(frame.model, 'eigenValues'));
menubar.pca.savePca.handle = pca8;


%               ----------------------------------------------------------- VIEW

% create all the submenus of the 'view' menu
menubar.view.grid.handle = uimenu(viewMenu, 'label', '&Grid', ...
                   'callback', @(~,~) toggleGridDisplay(frame), ...
                'accelerator', 'G');
menubar.view.markers.handle = uimenu(viewMenu, 'label', '&Markers', ...
                   'callback', @(~,~) toggleMarkerDisplay(frame), ...
                'accelerator', 'M');

menubar.view.zoom.handle = uimenu(viewMenu, 'label', '&Zoom', ...
                   'callback', @(~,~) toggleZoomMode(frame), ...
                  'separator', 'on', ...
                'accelerator', 'Z');
menubar.view.resetZoom.handle = uimenu(viewMenu, 'label', '&Reset zoom', ...
                   'callback', @(~,~) zoom('out'));

menubar.view.chooseGroupingFactor.handle = uimenu(viewMenu, 'label', 'Grouping Factor', ...
                   'callback', @(~,~) chooseGroupingFactor(frame), ...
                  'separator', 'on', ...
                     'enable', 'off');

menubar.view.exportDisplay.handle = uimenu(viewMenu, 'label', 'Export display', ...
                   'callback', @(~,~) saveView(frame), ...
                  'separator', 'on', ...
                     'enable', 'off');


%               ----------------------------------------------------------- 

% create all the submenus of the context menu of the futur
menubar.contextPanel.handle = contPmenu;
menubar.contextPanel.grid.handle = uimenu(contPmenu, 'label', '&Grid', ...
                     'callback', @(~,~) toggleGridDisplay(frame));
menubar.contextPanel.markers.handle  = uimenu(contPmenu, 'label', '&Markers', ...
                     'callback', @(~,~) toggleMarkerDisplay(frame));

menubar.contextPanel.zoom.handle = uimenu(contPmenu, 'label', '&Zoom', ...
                     'callback', @(~,~) toggleZoomMode(frame), ...
                    'separator', 'on');
menubar.contextPanel.resetZoom.handle = uimenu(contPmenu, 'label', '&Reset zoom', ...
                     'callback', @(~,~) zoom('out'));

%               ----------------------------------------------------------- 

% create the submenu of the selection list
menubar.contextList.handle = contLmenu;
menubar.contextList.swapSelection.handle = uimenu(contLmenu, 'label', '&Swap selection', ...
                     'callback', @(~,~) swapSelection);

frame.menuBar = menubar;


% -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
% ---------------------------------------------------------------------------- MENU CALLBACKS -----------------------------------------------------------------------------------------------------
% -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

function showTable(obj, varargin)
%SHOWFACTORS  open a new figure that displays the current factor Table
%
%   inputs :
%       - table : table that must be displayed
%   ouputs : none

    % create a figure and display the Table in it
    table = obj.model.factors;
    [hf, ht] = show(table);
    ht.Units = 'pixel';

    if ht.Extent(4) < obj.handles.figure.Position(4)
        % if the Height property of the uitable in which
        % the Table is displayed is lower than the total
        % Height of the MainFrame

        % match the size of the new figure to the size of the
        % uiTable and get the position where the figure
        % will be at the center of the MainFrame
        ht.Position = ht.Extent;
        pos = getMiddle(obj, ht.Position(3), ht.Position(4));
        
    else
        % get the position where the new figure will be at
        % the center of the MainFrame with the same Height
        % as the MainFrame and make the uiTable take all
        % the place it can
                                            % +16 = scrollbar
        pos = getMiddle(obj, ht.Extent(3)+16, obj.handles.figure.Position(4));
        ht.Units = 'normalized';
        ht.Position = [0 0 1 1];
    end
    % set the position of the new figure
    hf.Position = pos;
end

function swapSelection
%SWAPSELECTION  unselects all the selected polygons and selects all the unselected

    % get the complete list of polygons' name
    liste = frame.model.nameList;

    % memory allocation
    nonSelVal = zeros(length(liste), 1);

    for i = 1:length(liste)
        % for each polygons
        if ~ismember(i, get(frame.handles.list, 'value'))
            % if the polygon is not selected, save it
            nonSelVal(i) = i;
        end
    end

    % delete all the zeros of the not selected polygons list
    nonSelVal = nonSelVal(nonSelVal~=0);

    % set the unselected polygons as the selected polygons
    set(frame.handles.list, 'value', nonSelVal)
    frame.model.selectedPolygons = liste(nonSelVal);

    %update the view
    
    updateSelectedPolygonsDisplay(getActivePanel(frame));
end

end